<a href="https://colab.research.google.com/github/RomitGandhi/Python-project-1/blob/master/Norway_cars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

In [10]:
data = pd.read_csv("/norway_new_car_sales_by_make.csv")
# read csv file into dataframe


In [11]:
 data["Period"] = data["Year"].astype(str) + "-" + data["Month"].astype(str)

In [12]:
is_2012 =  data["Year"]<2012
print(is_2012.head())

0    True
1    True
2    True
3    True
4    True
Name: Year, dtype: bool


# New section

In [13]:
data1 = data.loc[is_2012]
print(data1.shape)


(2253, 6)


In [14]:
data.shape

(4377, 6)

In [15]:
data1  = pd.DataFrame(data1)

In [16]:
data1["Period"] = data1["Year"].astype(str) + "-" + data1["Month"].astype(str)

In [17]:
# We use the datetime formatting to make sure format is consistent 
data1["Period"] = pd.to_datetime(data1["Period"]).dt.strftime("%Y-%m")

In [18]:
print (data1["Period"]) 

0       2007-01
1       2007-01
2       2007-01
3       2007-01
4       2007-01
         ...   
2248    2011-12
2249    2011-12
2250    2011-12
2251    2011-12
2252    2011-12
Name: Period, Length: 2253, dtype: object


In [19]:
print (data1["Period"]) 

0       2007-01
1       2007-01
2       2007-01
3       2007-01
4       2007-01
         ...   
2248    2011-12
2249    2011-12
2250    2011-12
2251    2011-12
2252    2011-12
Name: Period, Length: 2253, dtype: object


In [20]:
df = pd.pivot_table(data=data1, values="Quantity", index="Make", columns="Period", aggfunc='sum', fill_value=0) 

In [21]:
df.head

<bound method NDFrame.head of Period         2007-01  2007-02  2007-03  ...  2011-10  2011-11  2011-12
Make                                      ...                           
Alfa Romeo          16        9       21  ...       27       26       34
Aston Martin         0        0        1  ...        0        2        0
Audi               599      498      682  ...      587      601      603
BMW                352      335      365  ...      639      591      328
Bentley              0        0        0  ...        0        0        0
Cadillac             0        1        4  ...        0        0        0
Chevrolet           20       35       52  ...        4        2        3
Chevrolet US         0        3        0  ...        0        0        1
Chrysler             4        5        3  ...        0        0        0
Citroen            263      247      239  ...      370      302      274
Dacia                0        0        0  ...        2        0        0
Daihatsu            1

In [22]:
df.to_excel("Clean Demand.xlsx")

In [23]:
def datasets(df, x_len=12, y_len=1, y_test_len=12):
  D = df.values
  periods = D.shape[1]
  loops = periods + 1 - x_len - y_len - y_test_len 
  print(loops)

In [24]:
datasets(df)

36


In [25]:
D = df.values
periods = D.shape[1]

In [26]:
x_len=12
y_len = 1
y_test_len=12
loops = periods + 1 - x_len - y_len - y_test_len

In [27]:
print(loops)

36


In [32]:
import numpy as np
train = []
for col in range(loops):
  train.append(D[:,col:col+x_len+y_len])

 

In [34]:
train = np.vstack(train)

In [35]:
train

array([[  16,    9,   21, ...,   18,   21,   15],
       [   0,    0,    1, ...,    0,    0,    0],
       [ 599,  498,  682, ...,  448,  462,  429],
       ...,
       [1117, 1894, 1287, ..., 1379, 1511,  668],
       [1571, 1524, 1411, ..., 1659, 1824, 1298],
       [1217,  652,  842, ...,  922,  939, 1314]])

In [36]:
X_train, Y_train = np.split(train,[x_len],axis=1)

In [37]:
X_train

array([[  16,    9,   21, ...,   10,   18,   21],
       [   0,    0,    1, ...,    0,    0,    0],
       [ 599,  498,  682, ...,  554,  448,  462],
       ...,
       [1117, 1894, 1287, ..., 1461, 1379, 1511],
       [1571, 1524, 1411, ..., 1575, 1659, 1824],
       [1217,  652,  842, ...,  827,  922,  939]])

In [38]:
Y_train

array([[  15],
       [   0],
       [ 429],
       ...,
       [ 668],
       [1298],
       [1314]])

In [40]:
 max_col_test = periods - x_len - y_len + 1
 test = []
 for col in range(loops,max_col_test):
  test.append(D[:,col:col+x_len+y_len])
 test = np.vstack(test)
 X_test, Y_test = np.split(test,[x_len],axis=1)

In [41]:
if y_len == 1:
 Y_train = Y_train.ravel()
 Y_test = Y_test.ravel()

In [42]:
Y_train

array([  15,    0,  429, ...,  668, 1298, 1314])

In [43]:
from sklearn.tree import DecisionTreeRegressor 
 
# — Instantiate a Decision Tree Regressor 
tree = DecisionTreeRegressor(max_depth=5,min_samples_leaf=5) 
 
# — Fit the tree to the training data 
tree.fit(X_train,Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=5, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [48]:
# Create a prediction based on our model 
Y_train_pred = tree.predict(X_train) 
 
# Compute the Mean Absolute Error of the model 
import numpy as np
MAE_tree = np.mean(abs(Y_train - Y_train_pred))/np.mean(Y_train) 
 
# Print the results 
print("Tree on train set MAE%:",round(MAE_tree*100,1))

Tree on train set MAE%: 17.8


In [50]:
Y_test_pred = tree.predict(X_test) 
MAE_test = np.mean(abs(Y_test - Y_test_pred))/np.mean(Y_test) 
print("Tree on test set MAE%:",round(MAE_test*100,1))


Tree on test set MAE%: 20.8
